# Data Preprocessing

In [40]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [41]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [42]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

C:\Users\SHADAAB\AppData\Local\conda\conda\envs\hello-tf\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\SHADAAB\AppData\Local\conda\conda\envs\hello-tf\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [43]:
#But now we will remove one dummy variable here to avoid falling into the dummy variable trap.

In [44]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [45]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# ANN

In [46]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [47]:
# Initialising the ANN
classifier = Sequential()

In [48]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
#relu=rectifier transfer function     
#units=no. of hidden layer. input+output/2.  11+1/2=6

In [49]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [50]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
#unit= 3 if you have 3 categories for dependent variable
#activation= 'softmax' softmax is actually the sigmoid function, but applied to a dependent variable that has more than two
#categories

# But here, we have two categories, two classes, so we are fine with the sigmoid function

In [51]:
# We are done adding the layers of our artificial neural network, and now what we're gonna do is to compile the whole 
# artificial neural network, that is basically applying stochastic gradient descent on the whole artificial neural network.
# That's what compiling means.

In [52]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [53]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 2s 282us/step - loss: 0.4793 - acc: 0.7964
Epoch 2/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.4100 - acc: 0.8232 0s - loss: 0.4
Epoch 3/100
8000/8000 [==============================] - 2s 198us/step - loss: 0.3952 - acc: 0.8274
Epoch 4/100
8000/8000 [==============================] - 1s 169us/step - loss: 0.3854 - acc: 0.8309
Epoch 5/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3797 - acc: 0.8306
Epoch 6/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.3750 - acc: 0.8436
Epoch 7/100
8000/8000 [==============================] - 1s 172us/step - loss: 0.3708 - acc: 0.8465
Epoch 8/100
8000/8000 [==============================] - 1s 172us/step - loss: 0.3674 - acc: 0.8490
Epoch 9/100
8000/8000 [==============================] - 2s 207us/step - loss: 0.3658 - acc: 0.8495
Epoch 10/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.363

8000/8000 [==============================] - 1s 143us/step - loss: 0.3379 - acc: 0.8616
Epoch 83/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3393 - acc: 0.8604
Epoch 84/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.3388 - acc: 0.8600
Epoch 85/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.3379 - acc: 0.8606
Epoch 86/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.3378 - acc: 0.8601
Epoch 87/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3377 - acc: 0.8602
Epoch 88/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.3378 - acc: 0.8617
Epoch 89/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3385 - acc: 0.8614
Epoch 90/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.3385 - acc: 0.8599
Epoch 91/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.3385 - acc: 0.8606
Epo

# Making predictions and evaluating the model


In [54]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [55]:
# Making the Confusion Matrix and classification report
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print('\n')
print(classification_report(y_test,y_pred))

[[1502   93]
 [ 191  214]]


              precision    recall  f1-score   support

           0       0.89      0.94      0.91      1595
           1       0.70      0.53      0.60       405

   micro avg       0.86      0.86      0.86      2000
   macro avg       0.79      0.74      0.76      2000
weighted avg       0.85      0.86      0.85      2000



In [56]:
# The accuracy is the number of correct predictions divided by the total number of predictions
# here correct predictions- 1539,146

In [57]:
(1539+146)/2000

0.8425

# Accuracy of our model is 84.5%

So, eventually, we can validate our model, and now the bank can use it to make a ranking of their customers, 
ranked by their probability to leave the bank, from the customer that has the highest probability to leave the bank,
down to the customer that has the lowest probability to leave the bank.

# Predicting a single new observation


In [58]:
"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""

'Predict if the customer with the following informations will leave the bank:\nGeography: France\nCredit Score: 600\nGender: Male\nAge: 40\nTenure: 3\nBalance: 60000\nNumber of Products: 2\nHas Credit Card: Yes\nIs Active Member: Yes\nEstimated Salary: 50000'

In [61]:
new_prediction = classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = (new_prediction > 0.5)

In [64]:
# Making the Confusion Matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

[[1502   93]
 [ 191  214]]


              precision    recall  f1-score   support

           0       0.89      0.94      0.91      1595
           1       0.70      0.53      0.60       405

   micro avg       0.86      0.86      0.86      2000
   macro avg       0.79      0.74      0.76      2000
weighted avg       0.85      0.86      0.85      2000



In [65]:
new_prediction

array([[False]])

# Therefore the customer doesn't leave the bank